apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service-2048-stage
bases:
- ../../base
resources:
  - 2048-namespace.yaml
  - 2048-service.yaml
patchesStrategicMerge:
- stage-deployment.yaml