apiVersion: v1
kind: Service
metadata:
  name: service-2048
  namespace: service-2048
spec:
  ports:
    - port: 8585
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "2048-app"

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: service-2048
  namespace: service-2048
spec:
  prefix: /
  service: service-2048:8585